# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'techTestZemoga' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for techTestZemoga
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'
  
  target 'techTestZemogaTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'techTestZemogaUITests' do
    # Pods for testing
  end

end
